version: '3'

services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox
    ports:
      - "50021:50021"
  aichat:
    build: .
    image: aichat
    container_name: aichat
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - voicevox